spring:
  application:
    name: website-backend
  
  datasource:
    url: jdbc:sqlite:${SQLITE_PATH:blog.db}
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  
  devtools:
    restart:
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.irku: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
